trigger:
- main

variables:
  TF_VERSION: '1.5.0'
  WORKING_DIR: 'Modules/Aks'
  SERVICE_CONNECTION: 'terraform-azure-connection'

stages:

# ================= INIT =================
- stage: Init
  displayName: "Terraform Init"

  jobs:
  - job: InitJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: "Install Terraform Manually"

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(WORKING_DIR)

        # REQUIRED FOR INIT (your version bug)
        backendServiceArm: $(SERVICE_CONNECTION)
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)

        backendAzureRmResourceGroupName: 'devbackendRG'
        backendAzureRmStorageAccountName: 'devbackendstorage12345'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

# ================= PLAN =================
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Init

  jobs:
  - job: PlanJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: "Install Terraform Manually"

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(WORKING_DIR)

        # ONLY THIS FOR PLAN
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)

# ================= APPLY =================
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - job: ApplyJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: "Install Terraform Manually"

    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(WORKING_DIR)

        # ONLY THIS FOR APPLY
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)
